version: '3' 
# Define the services/containers to be run
services:
  rest_api:
    build: test-nestjs
    ports:
        - '3000:3000'
    command: npm start
    depends_on: 
      - mongodb   
  data_db:
      build: mongodata
      links:
        - mongodb
  mongodb:
    image: mongo:4.0.0 
    ports:
      - '27017:27017'

